<a href="https://colab.research.google.com/github/Raju-kushwaha1230/ML/blob/main/Column_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv('/content/covid_toy.csv')

In [14]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [15]:
df['cough'].value_counts()

,count
cough,
Mild,62
Strong,38


In [16]:
df.isnull().sum()

,0
age,0
gender,0
fever,10
cough,0
city,0
has_covid,0


In [17]:
from sklearn.model_selection import train_test_split

In [39]:
X_train,X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2, random_state=0)

In [40]:
X_train.head()

,age,gender,fever,cough,city
43,22,Female,99.0,Mild,Bangalore
62,56,Female,104.0,Strong,Bangalore
3,31,Female,98.0,Mild,Kolkata
71,75,Female,104.0,Strong,Delhi
45,72,Male,99.0,Mild,Bangalore


# **Handling the Missing value in**

In [41]:
from sklearn.impute import SimpleImputer

In [42]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])


In [43]:
X_train_fever


array([[ 99.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.91549296],
       [100.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [100.91549296],
       [100.91549296],
       [104.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [103.        ],
       [104.        ],
       [ 99

In [44]:
X_train_fever.shape

(80, 1)

# **Ordinal Encoding**


In [45]:
from sklearn.preprocessing import OrdinalEncoder

In [46]:
df['cough'].value_counts()

,count
cough,
Mild,62
Strong,38


In [47]:
X_train['cough']

,cough
43,Mild
62,Strong
3,Mild
71,Strong
45,Mild
...,...
96,Strong
67,Mild
64,Mild
47,Mild


In [48]:
oe = OrdinalEncoder(categories=[['Mild','Strong']],  dtype= np.int32)
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.fit_transform(X_test[['cough']])


In [50]:
X_train_cough

array([[0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1]], dtype=int32)

## ** on CIty Column**

In [52]:
from sklearn.preprocessing import OneHotEncoder

In [53]:
df['city'].value_counts()

,count
city,
Kolkata,32
Bangalore,30
Delhi,22
Mumbai,16


In [54]:
ohe = OneHotEncoder(drop = 'first',sparse_output=False, dtype= np.int32)
X_train_city = ohe.fit_transform(X_train[['city']])
X_test_city = ohe.fit_transform(X_test[['city']])

In [57]:
X_train['city']

,city
43,Bangalore
62,Bangalore
3,Kolkata
71,Delhi
45,Bangalore
...,...
96,Kolkata
67,Bangalore
64,Mumbai
47,Bangalore


In [65]:
X_train_city

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 1],
       [1,

In [58]:
X_train_city.shape

(80, 3)

In [61]:
X_train['city']

,city
43,Bangalore
62,Bangalore
3,Kolkata
71,Delhi
45,Bangalore
...,...
96,Kolkata
67,Bangalore
64,Mumbai
47,Bangalore


# **OneHotEncoding on Gender and city**

In [66]:
ohe = OneHotEncoder(drop = 'first', sparse_output=False, dtype= np.int32)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

In [67]:
X_train_gender_city

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0,

In [68]:
X_train_gender_city.shape

(80, 4)

# **LabelEncoding on Target column**

In [69]:
from sklearn.preprocessing import LabelEncoder

In [71]:
le = LabelEncoder()
y_train_label = le.fit_transform(y_train)
y_test_label = le.fit_transform(y_test)

In [76]:
y_train

,has_covid
43,Yes
62,Yes
3,No
71,No
45,No
...,...
96,Yes
67,No
64,No
47,No


In [74]:
y_train_label

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [75]:
le.classes_

array(['No', 'Yes'], dtype=object)

# **Extracting the age**

In [77]:
X_train.head()

,age,gender,fever,cough,city
43,22,Female,99.0,Mild,Bangalore
62,56,Female,104.0,Strong,Bangalore
3,31,Female,98.0,Mild,Kolkata
71,75,Female,104.0,Strong,Delhi
45,72,Male,99.0,Mild,Bangalore


In [86]:
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

In [88]:
X_train_age

array([[22],
       [56],
       [31],
       [75],
       [72],
       [66],
       [14],
       [10],
       [24],
       [80],
       [24],
       [14],
       [59],
       [54],
       [11],
       [33],
       [64],
       [71],
       [10],
       [34],
       [27],
       [81],
       [27],
       [82],
       [65],
       [70],
       [40],
       [49],
       [49],
       [84],
       [38],
       [ 6],
       [60],
       [74],
       [16],
       [19],
       [65],
       [82],
       [80],
       [47],
       [75],
       [83],
       [51],
       [49],
       [48],
       [16],
       [34],
       [69],
       [51],
       [46],
       [42],
       [34],
       [44],
       [20],
       [ 5],
       [73],
       [12],
       [79],
       [83],
       [ 8],
       [23],
       [55],
       [65],
       [19],
       [50],
       [69],
       [23],
       [25],
       [ 5],
       [68],
       [47],
       [38],
       [73],
       [17],
       [64],
       [51],
       [65],

In [89]:
X_train_age.shape

(80, 1)

In [96]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city, X_train_cough),axis=1)
X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city,X_test_cough), axis=1)

In [97]:
X_train_transformed.shape

(80, 7)

In [98]:
X_test_transformed.shape

(20, 7)

In [102]:
X_train_transformed

array([[ 22.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 56.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 75.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 72.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 66.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 14.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 10.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 24.        ,  98.        ,   1.        ,   0.        ,
          1.    

# **Advanced way to do using ColumnTranformer**




In [103]:
from sklearn.compose import ColumnTransformer

In [108]:
df.sample(5)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
77,8,Female,101.0,Mild,Kolkata,No
95,12,Female,104.0,Mild,Bangalore,No
90,59,Female,99.0,Strong,Delhi,No
25,23,Male,NaN,Mild,Mumbai,No


In [121]:
transformer = ColumnTransformer(transformers=[
    ('trf1',SimpleImputer(),['fever']),
    ('trf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough'] ),
    ('trf3', OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32), ['gender','city'])
], remainder='passthrough')

In [123]:
X_train_Column_transform = transformer.fit_transform(X_train)

In [124]:
X_train_Column_transform

array([[ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  66.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  14.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  10.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          1.    

In [125]:
X_train_Column_transform.shape

(80, 7)

In [126]:
X_test_column_transform  = transformer.fit_transform(X_test)

In [127]:
X_test_column_transform

array([[100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  25.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  27.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  69.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [128]:
X_test_column_transform.shape

(20, 7)