<a href="https://colab.research.google.com/github/Raju-kushwaha1230/ML/blob/main/Encoding_Categorial_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **`Categrocal data`**
*Nominal data*  `and`  *Ordinal data*
                        : excellent - good - bad


# **`Ordinal Encoding`**



In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [5]:
df = pd.read_csv('/content/customer.csv')

In [7]:
df.sample(5)

,age,gender,review,education,purchased
17,22,Female,Poor,UG,Yes
10,98,Female,Good,UG,Yes
6,18,Male,Good,School,No
22,18,Female,Poor,PG,Yes
43,27,Male,Poor,PG,No


In [8]:
df = df.iloc[:,2:]

In [42]:
df

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No
5,Average,School,Yes
6,Good,School,No
7,Poor,School,Yes
8,Average,UG,No
9,Good,UG,Yes


In [13]:
from sklearn.preprocessing import OrdinalEncoder

In [15]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [17]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1:], test_size=0.2)

In [44]:
X_train

array([[2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [0., 2.]])

In [27]:
y_train.head()

,purchased
48,Yes
22,Yes
39,No
32,Yes
15,No


In [28]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [35]:
X_train = oe.transform(X_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [37]:
X_test = oe.transform(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [40]:
X_train

array([[2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [0., 2.]])

In [45]:
y_train

,purchased
48,Yes
22,Yes
39,No
32,Yes
15,No
2,No
27,No
24,Yes
20,Yes
1,No


In [47]:
from sklearn.preprocessing import  LabelEncoder

In [48]:
le = LabelEncoder()

In [49]:
le.fit(y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:93: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [51]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [52]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [53]:
y_train

array([1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0])